### ISSUE TITLE
空壳？

### ISSUE THREAD

**Issue by cccRaim** [paraself/WeappStore#1]

**Comment by paraself** [comment]
恩，实际上已经做完了，但是觉得api有些问题，而且有一些bug，就暂时没有传上来。

**Comment by cccRaim** [comment]
我自己已经仿照你的api做了一个同名的了- -

**Comment by paraself** [comment]
恩恩，蛮好的，够用就好。
我这边之后添加了一个把store转化成queryString用于创建分享页面的方法，
回头我清理好了，就发上来。
